# Site settings
author: Berto
title: Coding with no Experience
header-img: img/home-bg.png
email: robby.medina562@gmail.com
copyright_name: Berto
description: > # this means to ignore newlines until "baseurl:"
  My intro to coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  birdo562

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
